package com.kuro.visrelayfix;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.gameevent.TickEvent;

import java.util.Collections;

public final class VisRelayFixModContainer extends DummyModContainer {
    public VisRelayFixModContainer() {
        super(metadata());
    }

    private static ModMetadata metadata() {
        ModMetadata metadata = new ModMetadata();
        metadata.modId = "thaumcraftvisrelayfix";
        metadata.name = "Thaumcraft Vis Relay Fix";
        metadata.version = "1.1.21";
        metadata.authorList = Collections.singletonList("Kuro");
        metadata.description = "Repairs Thaumcraft vis relay graphs after chunk reloads.";
        metadata.autogenerated = false;
        return metadata;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        FMLCommonHandler.instance().bus().register(this);
        return true;
    }

    @Subscribe
    public void onServerStarting(FMLServerStartingEvent event) {
        VisRelayManualCommand.register(event);
    }

    @cpw.mods.fml.common.eventhandler.SubscribeEvent
    public void onServerTick(TickEvent.ServerTickEvent event) {
        if (event.phase == TickEvent.Phase.END) {
            VisRelayManualCommand.tick();
        }
    }
}
